### ISSUE TITLE
Set up CD

### ISSUE THREAD

**Issue by RyckmanApps** [RyckmanApps/Site-CRAI#1]
Todo. Set up Continuous Deployment (CD). 

Set Up GitHub Actions**: In your GitHub repository, you can create a new GitHub Actions workflow. This is done by creating a new file in the `.github/workflows` directory of your repository. The file should end with `.yml` or `.yaml`.

Configure the Workflow**: In the workflow file, you can specify that you want to deploy to Firebase whenever changes are pushed to your repository. Here's a basic example of what the workflow file might look like:

```yaml
name: Deploy to Firebase
on: [push]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```

In this example, the workflow is triggered on every push. It checks out your repository, installs any dependencies, builds your project, and then deploys to Firebase. The `FIREBASE_TOKEN` is a secret that you need to set in your GitHub repository settings.

Set Firebase Token: You'll need to add your Firebase token as a secret in your GitHub repository. You can generate a new Firebase token by running `firebase login:ci` in your local development environment. Then, go to the "Secrets" section of your repository settings on GitHub and add a new secret with the name `FIREBASE_TOKEN` and the value of the token you just generated.

**Push Changes**: Now, whenever you push changes to your repository, GitHub Actions will automatically deploy your project to Firebase.

Remember to replace the `npm run build` command with the actual build command for your project, if it's different. Also, if you're deploying more than just hosting (like functions, firestore rules, etc.), you'll need to adjust the `--only hosting` flag in the deploy command.
